In [2]:
import numpy as np
import cv2

In [ ]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

In [ ]:
img = cv2.imread('OIP.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [ ]:
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
faces

In [ ]:
# Initialize an eye counter for naming the saved images
eye_counter = 0

for (x, y, w, h) in faces:
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]

    # Detect eyes in the face region
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex, ey, ew, eh) in eyes:
        eye_img = roi_color[ey:ey+eh, ex:ex+ew]  # Extract the eye region
        print(eye_img)
        # Save the extracted eye image
        cv2.imwrite(f'eye_{eye_counter}.jpg', eye_img)
        eye_counter += 1  # Increment the counter for the next eye image

In [4]:
def return_eye(imag):
    img = imag
    face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    # Initialize an eye counter for naming the saved images
    eye_counter = 0
    for (x, y, w, h) in faces:
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]

        # Detect eyes in the face region
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex, ey, ew, eh) in eyes:
            eye_img = roi_color[ey:ey+eh, ex:ex+ew]  # Extract the eye region
            return eye_img

In [5]:
print(return_eye(img))

[[[145 171 218]
  [145 168 216]
  [142 165 213]
  ...
  [141 173 216]
  [136 168 209]
  [132 164 207]]

 [[136 162 208]
  [134 160 206]
  [132 158 204]
  ...
  [133 163 204]
  [131 162 201]
  [135 165 206]]

 [[129 155 201]
  [128 155 199]
  [127 153 199]
  ...
  [120 147 184]
  [119 146 183]
  [126 153 190]]

 ...

 [[160 181 236]
  [139 163 221]
  [124 147 203]
  ...
  [132 161 205]
  [131 160 204]
  [134 163 207]]

 [[160 180 235]
  [150 172 230]
  [142 162 219]
  ...
  [132 161 205]
  [130 159 203]
  [130 159 203]]

 [[165 182 238]
  [163 183 241]
  [158 176 235]
  ...
  [135 164 208]
  [134 163 207]
  [134 163 207]]]


In [7]:
 cv2.imshow('Extracted Eye', return_eye(img))

In [3]:
img = cv2.imread('OIP.jpg')